version: '3'
services:
  dynamoDB:
    image: amazon/dynamodb-local
    volumes:
      - "/Users/ruizhang/Development/dynamodb_local_latest/dynamodb:/data/"
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]

  qor:
    depends_on:
      - dynamoDB
    image: qor-started
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
